"""Generate DDL from schema_report.json + config.py.

Outputs two files under db/init/:
  01_schema.sql       - schema, extensions, CREATE TABLE statements (no FKs / indexes yet)
  02_constraints.sql  - PK constraints, FK constraints, FK indexes, smart comments

The order matters because the loader applies 01 → COPY data → 02.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import config as cfg
from transform import plan_table

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent

# A few PG keywords used as columns in the dataset
PG_RESERVED = {"name", "left", "right", "user"}


def quote_ident(name: str) -> str:
    if name.lower() in PG_RESERVED or not re.match(r"^[a-z_][a-z0-9_]*$", name):
        return f'"{name}"'
    return name


def build_create_table(plan, schema: str) -> str:
    lines = [f"CREATE TABLE {schema}.{quote_ident(plan.pg_table)} ("]
    col_lines = []
    for c in plan.columns:
        nn = "" if c.nullable else " NOT NULL"
        col_lines.append(f"  {quote_ident(c.pg_name)} {c.pg_type}{nn}")
    lines.append(",\n".join(col_lines))
    lines.append(");")
    return "\n".join(lines)


def build_pk(plan, schema: str) -> str:
    if not plan.pk:
        return ""
    cols = ", ".join(quote_ident(c) for c in plan.pk)
    return (
        f"ALTER TABLE {schema}.{quote_ident(plan.pg_table)} "
        f"ADD CONSTRAINT {plan.pg_table}_pkey PRIMARY KEY ({cols});"
    )


def build_fks(plan, schema: str) -> list[str]:
    out = []
    for col, target in plan.fks:
        if target not in cfg.PK_BY_TABLE:
            # target table is not in our export — comment-only fk
            out.append(
                f"-- {plan.pg_table}.{col} references missing table {target} (left as plain uuid)"
            )
            continue
        cname = f"{plan.pg_table}_{col}_fkey"
        out.append(
            f"ALTER TABLE {schema}.{quote_ident(plan.pg_table)} "
            f"ADD CONSTRAINT {cname} FOREIGN KEY ({quote_ident(col)}) "
            f"REFERENCES {schema}.{quote_ident(target)} (id) "
            f"ON DELETE NO ACTION ON UPDATE NO ACTION;"
        )
        out.append(
            f"CREATE INDEX {plan.pg_table}_{col}_idx "
            f"ON {schema}.{quote_ident(plan.pg_table)} ({quote_ident(col)});"
        )
    return out


def build_geo(plan, schema: str) -> str | None:
    """If the table has a synthesized location column, build a GiST index on it."""
    if not plan.geo:
        return None
    out_col = plan.geo["out_col"]
    return (
        f"CREATE INDEX {plan.pg_table}_{out_col}_gix "
        f"ON {schema}.{quote_ident(plan.pg_table)} USING GIST ({quote_ident(out_col)});"
    )


def main():
    report = json.loads((HERE / "schema_report.json").read_text())

    schema_sql_parts: list[str] = []
    constraints_sql_parts: list[str] = []

    schema_sql_parts.append("-- Generated by migration/build_schema.py — do not edit by hand.")
    schema_sql_parts.append(f"CREATE SCHEMA IF NOT EXISTS {cfg.PG_SCHEMA};")
    schema_sql_parts.append("CREATE EXTENSION IF NOT EXISTS postgis;")
    schema_sql_parts.append("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")
    schema_sql_parts.append(f"SET search_path TO {cfg.PG_SCHEMA}, public;")
    schema_sql_parts.append("")

    constraints_sql_parts.append("-- Generated by migration/build_schema.py — do not edit by hand.")
    constraints_sql_parts.append(f"SET search_path TO {cfg.PG_SCHEMA}, public;")
    constraints_sql_parts.append("")

    plans = []
    for table, t_report in report["sheets"].items():
        if "columns" not in t_report:
            print(f"  !! {table}: skipping (analyzer error)", file=sys.stderr)
            continue
        plan = plan_table(t_report, table)
        plans.append(plan)

    # CREATE TABLEs
    for plan in plans:
        schema_sql_parts.append(f"-- {plan.pg_table}")
        if plan.drop_log:
            schema_sql_parts.append("-- dropped columns:")
            for d in plan.drop_log:
                schema_sql_parts.append(f"--   {d}")
        if plan.rename_log:
            schema_sql_parts.append("-- renames:")
            for old, new, why in plan.rename_log:
                schema_sql_parts.append(f"--   {old} -> {new}  ({why})")
        schema_sql_parts.append(build_create_table(plan, cfg.PG_SCHEMA))
        schema_sql_parts.append("")

    # All PKs first — required before any FK can reference them.
    constraints_sql_parts.append("-- ===== primary keys =====")
    for plan in plans:
        pk = build_pk(plan, cfg.PG_SCHEMA)
        if pk:
            constraints_sql_parts.append(pk)
    constraints_sql_parts.append("")

    # Then FKs + supporting indexes
    constraints_sql_parts.append("-- ===== foreign keys + indexes =====")
    for plan in plans:
        lines = build_fks(plan, cfg.PG_SCHEMA)
        if lines:
            constraints_sql_parts.append(f"-- {plan.pg_table}")
            constraints_sql_parts.extend(lines)

    # Geo indexes
    constraints_sql_parts.append("")
    constraints_sql_parts.append("-- ===== spatial indexes =====")
    for plan in plans:
        geo = build_geo(plan, cfg.PG_SCHEMA)
        if geo:
            constraints_sql_parts.append(geo)

    # Smart comments — control PostGraphile's GraphQL projection.
    # Hide the geography column (frontends use lat/lon numerics).
    constraints_sql_parts.append("")
    constraints_sql_parts.append("-- ===== postgraphile smart comments =====")
    for plan in plans:
        if plan.geo:
            constraints_sql_parts.append(
                f"COMMENT ON COLUMN {cfg.PG_SCHEMA}.{quote_ident(plan.pg_table)}."
                f"{quote_ident(plan.geo['out_col'])} IS E'@omit\\nRaw PostGIS geography; consume lat/lon via GraphQL instead.';"
            )

    init_dir = REPO_ROOT / "db" / "init"
    init_dir.mkdir(parents=True, exist_ok=True)
    (init_dir / "01_schema.sql").write_text("\n".join(schema_sql_parts))
    (init_dir / "02_constraints.sql").write_text("\n".join(constraints_sql_parts))
    print(f"wrote {init_dir / '01_schema.sql'}")
    print(f"wrote {init_dir / '02_constraints.sql'}")

    # Also dump per-table plan as JSON for the extractor to consume
    plans_dump = []
    for plan in plans:
        plans_dump.append({
            "source_sheet": plan.source_sheet,
            "pg_table": plan.pg_table,
            "columns": [
                {
                    "source_idx": c.source_idx,
                    "source_name": c.source_name,
                    "pg_name": c.pg_name,
                    "pg_type": c.pg_type,
                    "is_pk": c.is_pk,
                    "is_fk": c.is_fk,
                    "nullable": c.nullable,
                    "strip_spaces": c.strip_spaces,
                }
                for c in plan.columns
            ],
            "pk": plan.pk,
            "fks": plan.fks,
            "geo": plan.geo,
        })
    (HERE / "plans.json").write_text(json.dumps(plans_dump, indent=2))
    print(f"wrote {HERE / 'plans.json'}")


if __name__ == "__main__":
    main()
